# Generated by Django 3.2 on 2023-07-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=200)),
                ('poster', models.CharField(max_length=200)),
            ],
        ),
    ]
