# Generated by Django 2.2 on 2023-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
