# Generated by Django 3.2 on 2023-07-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_movie'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='douban_,ovie',
        ),
    ]
