# Generated by Django 3.2 on 2023-07-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_movie_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='douban_movie',
        ),
    ]
