# Generated by Django 3.2 on 2023-07-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_movie_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
